'use client';

import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';

const SCORE_SETS = [
  [8, 7, 9, 6, 8, 7, 5, 8, 7, 6],
  [5, 9, 6, 9, 5, 8, 8, 6, 9, 8],
  [9, 6, 8, 5, 9, 6, 7, 9, 6, 7],
  [7, 8, 5, 8, 7, 9, 9, 7, 8, 5],
];

const LABELS = [
  { short: 'Intent', def: 'CSI Alignment - checks if the content matches the exact search intent. Evaluates how precisely the article answers what the user is looking for.' },
  { short: 'Density', def: 'Information Density - ratio of concrete facts and numbers to filler. The more verifiable claims, the higher the score.' },
  { short: 'KGraph', def: 'Knowledge Graph - completeness of entity-attribute-value (EAV) structure. Measures how thoroughly the article describes key objects and their properties.' },
  { short: 'BLUF', def: 'Bottom Line Up Front - whether the key answer appears in the first sentences of each section. RAG systems prefer content with the answer upfront.' },
  { short: 'Chunks', def: 'Chunk Optimization - section autonomy. Each section should be understandable without the context of the rest of the article (optimum: 200-500 words).' },
  { short: 'CoR', def: 'Cost of Retrieval - ease of information extraction by AI. Evaluates heading structure, tables, lists and bold formatting that help AI retrieve facts.' },
  { short: 'TF-IDF', def: 'TF-IDF - domain terminology saturation. Compares article vocabulary with top 10 SERP - the more specialized terms, the higher the score.' },
  { short: 'Roles', def: 'Semantic Roles - narrative perspective. Measures whether the central entity (product/service) plays an active subject role in sentences.' },
  { short: 'AIO', def: 'AI Overview Coverage - checks if the article answers all sub-queries generated by AI around the main topic.' },
  { short: 'Effort', def: 'Editorial Effort - evaluates content structure and formatting: length, images, video, lists, tables, heading hierarchy, highlights. Compared against SERP competition.' },
];

export default function RadarIllustrationEN({ maxWidth = 220 }: { maxWidth?: number }) {
  const cx = 150, cy = 150, r = 96, axes = 10;
  const [scoreIdx, setScoreIdx] = useState(0);
  const [hoveredIdx, setHoveredIdx] = useState<number | null>(null);

  useEffect(() => {
    const id = setInterval(() => setScoreIdx(i => (i + 1) % SCORE_SETS.length), 2400);
    return () => clearInterval(id);
  }, []);

  const getPoint = (index: number, value: number) => {
    const angle = (Math.PI * 2 * index) / axes - Math.PI / 2;
    const dist = (value / 10) * r;
    return { x: cx + dist * Math.cos(angle), y: cy + dist * Math.sin(angle) };
  };

  const scores = SCORE_SETS[scoreIdx];
  const dataPoints = scores.map((s, i) => getPoint(i, s));
  const dataPath = dataPoints.map((p, i) => `${i === 0 ? 'M' : 'L'}${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(' ') + 'Z';

  const labelPositions = LABELS.map((_, i) => {
    const p = getPoint(i, 13);
    return { xPct: (p.x / 300) * 100, yPct: (p.y / 300) * 100 };
  });

  return (
    <div style={{ position: 'relative', width: '100%', maxWidth }}>
      <svg viewBox="0 0 300 300" className="w-full">
        {[2, 4, 6, 8, 10].map((level) => {
          const pts = Array.from({ length: axes }, (_, i) => getPoint(i, level));
          return (
            <path key={level}
              d={pts.map((p, i) => `${i === 0 ? 'M' : 'L'}${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(' ') + 'Z'}
              fill="none" stroke="#eceff3" strokeWidth="1" />
          );
        })}
        {Array.from({ length: axes }, (_, i) => {
          const p = getPoint(i, 10);
          return <line key={i} x1={cx} y1={cy} x2={p.x} y2={p.y} stroke="#eceff3" strokeWidth="1" />;
        })}
        <motion.path d={dataPath} fill="rgba(11,121,131,0.08)" stroke="#0b7983" strokeWidth="1.5" animate={{ d: dataPath }} transition={{ duration: 0.9, ease: 'easeInOut' }} />
        {dataPoints.map((p, i) => (
          <motion.circle key={i} r="3" fill="#0b7983" animate={{ cx: p.x, cy: p.y }} transition={{ duration: 0.9, ease: 'easeInOut' }} />
        ))}
        {LABELS.map((label, i) => {
          const p = getPoint(i, 13);
          const isHovered = hoveredIdx === i;
          const textWidth = label.short.length * 4.5;
          return (
            <g key={i} style={{ cursor: 'default' }} onMouseEnter={() => setHoveredIdx(i)} onMouseLeave={() => setHoveredIdx(null)}>
              <text x={p.x - 4} y={p.y} textAnchor="middle" dominantBaseline="middle" fill={isHovered ? '#0b7983' : '#0d0d12'} fontSize="9.5" fontWeight="700" fontFamily="Inter,system-ui,sans-serif" style={{ transition: 'fill 0.15s' }}>
                {label.short}
              </text>
              <circle cx={p.x + textWidth + 1} cy={p.y} r="5" fill={isHovered ? 'rgba(11,121,131,0.15)' : 'rgba(164,172,185,0.15)'} stroke={isHovered ? '#0b7983' : '#a4acb9'} strokeWidth="0.8" style={{ transition: 'fill 0.15s, stroke 0.15s' }} />
              <text x={p.x + textWidth + 1} y={p.y + 0.5} textAnchor="middle" dominantBaseline="middle" fill={isHovered ? '#0b7983' : '#a4acb9'} fontSize="6.5" fontWeight="600" fontFamily="Inter,system-ui,sans-serif" style={{ transition: 'fill 0.15s' }}>i</text>
            </g>
          );
        })}
      </svg>

      {hoveredIdx !== null && (() => {
        const { xPct, yPct } = labelPositions[hoveredIdx];
        const isBottomHalf = yPct > 55;
        const isRightHalf = xPct > 60;
        const isLeftHalf = xPct < 40;
        const translateX = isRightHalf ? '-100%' : isLeftHalf ? '0%' : '-50%';
        const translateY = isBottomHalf ? 'calc(-100% - 6px)' : '8px';
        return (
          <div style={{ position: 'absolute', left: `${xPct}%`, top: `${yPct}%`, transform: `translate(${translateX}, ${translateY})`, background: '#0b7983', color: '#ffffff', fontSize: 11, fontFamily: 'Inter,system-ui,sans-serif', lineHeight: 1.55, borderRadius: 7, padding: '8px 11px', width: 180, pointerEvents: 'none', zIndex: 20, boxShadow: '0 4px 16px rgba(0,0,0,0.18)' }}>
            {LABELS[hoveredIdx].def}
          </div>
        );
      })()}
    </div>
  );
}
